---

hostname: ubuntu18
user_groups:
  - name: hogeg
    gid: 1001
  - name: fugag
    gid: 1002
users:
  - name: hoge
    groups:
      - hogeg
      - sudo
  - name: fuga
    groups:
      - fugag
packages:
  - vim
  - curl
  - ufw
  - jq
  - sysstat
  - telnet
  - make
  - libcurses-ui-perl
  - libterm-readkey-perl
  - libcurses-perl
ssh:
  port: 2222
  permit_root_login: "without-password"
  password_authentication: "no"
  use_pam: "yes"
network:
  fw:
    rules:
      - rule: allow
        proto: tcp
        from_ip: any
        to_port: 80
      - rule: allow
        proto: tcp
        from_ip: any
        to_port: 443
      - rule: allow
        proto: tcp
        from_ip: any
        to_port: 2222
    policy: deny
journald:
  storage: persistent
  system_max_use: 1000
dns:
  ips:
    - 8.8.8.8
    - 8.8.4.4