---

- name: Put chrony config
  template:
    src: chrony.conf
    dest: /etc/chrony/chrony.conf

- name: Restart chronyd
  systemd:
    name: chronyd
    state: restarted
    enabled: yes

- name: Start chronyd automaticaly
  check_mode: no
  command: sysv-rc-conf chronyd on