---

- name: Import netplan playbook
  import_tasks: netplan.yml

- name: Import ufw playbook
  import_tasks: fw.yml

- name: Put DNS config
  template:
    src: resolved.conf
    dest: /etc/systemd/resolved.conf

- name: Restart service systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: yes